project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('radio.urls',namespace='radio')),
]

radio/urls.py
from django.urls import path
from . import views




app_name='radio'
urlpatterns = [
path('', views.homepage, name='homepage'),
path('doctor-dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
path('create-account/', views.create_account_page, name='create_account'),
path('login/', views.login_page, name='login'),

]

radio/models.py
from django.db import models
from django.contrib.auth.models import User

class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    gender = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    birth_date = models.DateField()
    

    def __str__(self):
        return self.name

radio/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, 'radio/index.html')


from django.shortcuts import render

def doctor_dashboard(request):
    # Add any necessary logic or data retrieval here
    return render(request, 'radio/doctor_dashboard.html')


from django.shortcuts import render
from django.contrib.auth.models import User
from .models import Doctor

def create_account_page(request):
    if request.method == 'POST':
        # Get the values from the form
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        repeat_password = request.POST.get('repeat_password')
        gender = request.POST.get('gender')
        phone_number = request.POST.get('phone_number')
        address = request.POST.get('address')
        birth_date = request.POST.get('birth_date')
       

        # Check if passwords match
        if password == repeat_password:
            # Save the user details in the database
            # Create a User object and save it
            user = User.objects.create_user(email=email, password=password)
            user.first_name = name
            user.save()

            # Save the additional details in the Doctor model
            doctor = Doctor(
                user=user,
                name=name,
                email=email,
                gender=gender,
                phone_number=phone_number,
                address=address,
                birth_date=birth_date,
                
            )
            doctor.save()

            return render(request, 'radio/create_account.html', {'success': True})
        else:
            return render(request, 'radio/create_account.html', {'error': 'Passwords do not match'})
    else:
        return render(request, 'radio/create_account.html')

def login_page(request):
    return render(request, 'radio/login.html')

radio/templates/radio/Login.html
{% extends 'layouts/login_base.html' %}					



{% block content %}
{% include "radio/navbar.html" %}
<form method="post" action="{% url 'radio:homepage' %}" class="validate-form" id="login-form">
    {% csrf_token %}

    <div class="wrap-input100 validate-input">
        <input class="input100" type="text" name="username" id="username" required="">
        <span class="focus-input100"></span>
        <span class="label-input100">Username</span>
    </div>

    <div class="wrap-input100 validate-input">
        <input class="input100" type="password" name="password" id="password" required="">
        <span class="focus-input100"></span>
        <span class="label-input100">Password</span>
    </div>

    <div class="flex-sb-m w-full p-t-3 p-b-32">
        <div class="contact100-form-checkbox">
            <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember">
            <span class="label-checkbox100" for="ckb1">
                Remember Me
            </span>
        </div>

        <div>
            <a href="url 'account:send_resetting_mail' %}" class="txt1">
                Forgot Password?
            </a>
        </div>
    </div>

    <div class="container-login100-form-btn mb-10">
        <button class="login100-form-btn" type="submit">
            {% if user.groups.exists %}
                {% if user.groups.all.0.name == 'Doctor' %}
                    <a href=" url 'doctor:doctor_dashboard' %}">Login</a>
                {% elif user.groups.all.0.name == 'Receptionist' %}
                    <a href=" url 'receptionist:receptionist_dashboard' %}">Login</a>
                {% elif user.groups.all.0.name == 'Radiologist' %}
                    <a href=" url 'radiologist:radiologist_dashboard' %}">Login</a>
                {% else %}
                    <a href=" url 'radio:homepage' %}">Login</a>
                {% endif %}
            {% else %}
                <a href="url 'radio:homepage' %}">Login</a>
            {% endif %}
        </button>
    </div>
    

    <br>

    <div>
        <span class="login100-form-title mt-10">
            <span class="h6">New here?</span>
            <a href=" url 'account:create_account' %}">
                <span class="h6">Doctor Create Account</span>
            </a>
        </span>
    </div>
</form>

				
    {% endblock %}

	
		

radio/templates/radio/create_account.html
{% extends 'layouts/login_base.html' %}	


    {% block content %}
                <form method="POST" action="" class="validate-form" id="register_form"  
                 id= "registration-form" >
                 {% csrf_token %}
                   <span class="login100-form-title p-b-20 p-t-20">
                       Create Account
                   </span>
                   
                   <div class="wrap-input100 validate-input ">
                       <input class="input100" type="text" name="name" value="" required="">
                       <span class="focus-input100"></span>
                       <span class="label-input100">Name</span>
                   </div>
               
                   <div class="validate-input">
                   <div class="row form-group">
                           <h5 class="col-lg-3 col-md-3 col-sm-3">
                               Role      
               </h5>
               <div class="col-lg-9 col-md-9 col-sm-9 d-inline">
               <input type="radio" name="Role" id="Admin" value="Admin"
                required=""> <label for="Admin" class="d-inline">Admin</label>
               <br>
               <input type="radio" name="Role" id="Doctor" value="Doctor" required=""> 
               <label for="Doctor" class="d-inline">Doctor<br>
               <input type="radio" name="Role" id="Receptionist" value="Receptionist" required="">
                <label for="Receptionist" class="d-inline">Receptionist</label><br>
               <input type="radio" name="Role" id="fTechnicians" value="Technicians" required=""> 
               <label for="Technicians" class="d-inline">Technicians<br>
               <input type="radio" name="Role" id="fRadiologist" value="Radiologist" required="">
                <label for="fRadiologist" class="d-inline">Radiologist<br>
               </label>
               </div>
               </div>
                   </div>
               
                   <div class="wrap-input100 validate-input ">
                       <input class="input100" type="text" name="phone" value="" required="">
                       <span class="focus-input100"></span>
                       <span class="label-input100">User Name</span>
                   </div>
               
                   <div class="wrap-input100 validate-input ">
                       <input class="input100" type="email" name="email" value="" required="">
                       <span class="focus-input100"></span>
                       <span class="label-input100">Email</span>
                   </div>
               <div class="wrap-input100 validate-input ">
                   <input class="input100" type="password" name="password" required="">
                   <span class="focus-input100"></span>
                   <span class="label-input100">Password</span>
               </div>
               
               <div class="wrap-input100 validate-input ">
                   <input class="input100" type="password" name="confirm_password" required="">
                   <span class="focus-input100"></span>
                   <span class="label-input100">Confirm Password</span>
               </div>
                            
                            <a href="" class="btn btn-primary">
                              <button type="button" class="btn btn-primary">Create Account</button>
                            </a>
                  
                              </form>
       {% endblock %}
                

radio/templates/radio/doctor_base.html
{% extends 'layouts/dashboard_users.html' %}
   
{% load static %}

    
{% block sidebar %}

  
  
  <!-- Sidebar user panel (optional) -->
  <div class="user-panel mt-3 pb-3 mb-3 d-flex">
    <div class="image">
      <img src="./Extreme Radiology _ Dashboard_files/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
    </div>
    <div class="info">
      <a href="https://radiology.extremelab.tech/patient#" class="d-block">
         
          saror<br>
          Code: 1593914720
                    </a>
    </div>
  </div>
  <!-- Sidebar Menu -->
  <!-- Admin sidebar -->
            <nav class="mt-2">
<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
<li class="nav-item">
  <a href="{% url 'radio:doctor_dashboard' %}" class="nav-link " id="dashboard">
      <i class="nav-icon fas fa-th"></i>
      <p>
          Dashboard
      </p>
  </a>
</li>

<li class="nav-item">
  <a href=" url 'radio:doctor_profile' %}" class="nav-link" id="profile">
    <i class="nav-icon fas fa-user-circle"></i>
    <p>
      Profile
    </p>
  </a>
</li>


<li class="nav-item">
    <a href=" url 'radio:booking' %}" class="nav-link" id="bookings">
      <i class="nav-icon fas fa-calendar"></i>
      <p>
        Requests
      </p>
    </a>
  </li>
  
<li class="nav-item">
  <a href=" url 'doctor:reports' %}" class="nav-link" id="groups">
    <i class="nav-icon fas fa-flask"></i>
    <p>
      Reports
    </p>
  </a>
</li>

<li class="nav-item">
  <a href=" url 'doctor:tests_library' %}" class="nav-link" id="tests_library">
    <i class="fas fa-book-medical nav-icon"></i>
    <p>
      Tests Library
    </p>
  </a>
</li>




</ul>
</nav>                <!-- \Patient sidebar -->
<!-- /.sidebar-menu -->
</div></div></div><div class="os-scrollbar os-scrollbar-horizontal os-scrollbar-unusable os-scrollbar-auto-hidden"><div class="os-scrollbar-track"><div class="os-scrollbar-handle" style="width: 100%; transform: translate(0px, 0px);"></div></div></div><div class="os-scrollbar os-scrollbar-vertical os-scrollbar-auto-hidden os-scrollbar-unusable"><div class="os-scrollbar-track"><div class="os-scrollbar-handle" style="height: 100%; transform: translate(0px, 0px);"></div></div></div><div class="os-scrollbar-corner"></div></div>
</aside>



{% endblock sidebar %}
        



{% block content %}
    
{% endblock content %}

radio/templates/radio/doctor_dashboard.html
{% extends 'radio/doctor_base.html' %}


{% block content %}

{% include "radio/navbar.html" %}
<!-- /.sidebar -->
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="min-height: 406.844px;">
      <!-- Content Header (Page header) -->
      <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">
            <i class="nav-icon fas fa-th"></i>
            &nbsp;doctor -Dashboard</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item active">Dashboard</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <div class="callout callout-success">
    <h5 class="text-success">
        <i class="fa fa-check"></i> Success
    </h5>
    <p>
        Login success
    </p>
</div>


          <!-- Small boxes (Stat box) -->
<div class="row">
    <!-- ./col -->
    <div class="col-lg-4">
        <!-- small box -->
        <div class="small-box bg-primary">
          <div class="inner">
            <h3>42</h3>
            <p>Total Reports</p>
          </div>
          <div class="icon">
            <i class="fa fa-layer-group"></i>
          </div>
        </div>
      </div>
      <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-4">
        <!-- small box -->
        <div class="small-box bg-warning">
          <div class="inner">
            <h3>30</h3>
            <p>Pending Reports</p>
          </div>
          <div class="icon">
            <i class="fa fa-pause-circle"></i>
          </div>
        </div>
      </div>
      <!-- ./col -->
      <!-- ./col -->
      <div class="col-lg-4">
        <!-- small box -->
        <div class="small-box bg-success">
          <div class="inner">
            <h3>12</h3>
            <p>Completed Reports</p>
          </div>
          <div class="icon">
            <i class="fa fa-check"></i>
          </div>
        </div>
      </div>
      <!-- ./col -->
  </div>
  <!-- /.row -->
  <div id="sidebar-overlay"></div></div>
<!-- /.content-wrapper -->

<input type="hidden" id="system_currency" value="USD">
</div><!-- /.container-fluid -->
</section>
{% endblock content %}

radio/templates/radio/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    
{% include "radio/navbar.html" %}
    
    <section class="hero">
        <div class="container">
            <img src="{% static 'images/hosp_00001247.jpg' %}" alt="Hero Image">
            <h1 class="text-center">Welcome to Alkmikwa Radiology Center</h1>
        </div>
    </section>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

radio/templates/radio/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="#">Radiology Management System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'radio:homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'radio:doctor_dashboard' %}">Doctor Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'radio:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'radio:create_account' %}">Create Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" url 'radio:logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/layouts/dashboard.html
<!-- dashboard.html -->

{% extends "layouts/dashboard_base" %}

{% block content %}
<div class="sidebar">
  <!-- sidebar content here -->
</div>

{% endblock %}

templates/layouts/login_base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/icon-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/hamburgers.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animsition.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
</head>
<body>
   
	<body data-new-gr-c-s-check-loaded="14.1027.0" data-gr-ext-installed="">
	

		<div class="limiter">
<div class="container-login100">
<div class="wrap-login100">
<div class="login100-more" style="background-image: url({% static 'images/hosp_00001247.jpg' %});"> 
</div>

<div class="login100-form">



	<div class="container-login100-form-btn mb-4">
		<div class="dropdown text-uppercase">
			<button class="btn btn-default dropdown-toggle text-uppercase" 
				type="button" id="dropdownMenuButton" 
				data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<i class="fa fa-globe"></i>
				<span id="langText">en</span>
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				<a class="dropdown-item" href=" url 'account:login_base' %}" onclick="setLang('en')">
					en
				</a>
				<a class="dropdown-item" href=" url 'account:arabic_login' %}" onclick="setLang('ar')">
					ar
				</a> 
			</div>
		</div>
	</div>
	

<span class="login100-form-title p-b-30">
<img src="{% static 'images/logo.png' %}" height="188">
</span>
<script>
	function setLang(lang) {
		document.getElementById("langText").innerHTML = lang;
	}
</script>
<script>
	$(document).ready(function() {
	  // Get the current language from the URL
	  var lang = window.location.pathname.split('/')[2];
	  
	  // Set the text of the dropdown button based on the current language
	  var dropdownButton = $('#dropdownMenuButton');
	  if (lang == 'ar') {
		dropdownButton.html('<i class="fa fa-globe"></i> ar');
	  } else {
		dropdownButton.html('<i class="fa fa-globe"></i> en');
	  }
	  
	  // Handle the click event for the language links
	  $('.lang-link').click(function(event) {
		event.preventDefault(); // Prevent the default link behavior
		
		// Get the new language from the link href attribute
		var newLang = $(this).attr('href').split('/')[2];
		
		// Set the language cookie to remember the user's choice
		document.cookie = 'lang=' + newLang + '; path=/';
		
		// Reload the page with the new language
		window.location.href = window.location.pathname.replace(lang, newLang);
	  });
	});
	</script>



{% block content %}
    
{% endblock content %}
    
	
{% block footer %}
	<div class="container-login100-form-btn">
						
		<div class="row pt-4">
<div class="col-lg-12">
<h6 class="text-center mb-3">- Follow Us -</h6>
</div>
<div class="col-lg-12">
<ul class="social text-center">
			  <li class="d-inline">
<a href="#">
	<img src="{% static 'images/facebook.png' %}" width="40px">
</a>
</li>
						<li class="d-inline">
<a href="#">
	<img src="{% static 'images/twitter.png' %}" width="40px">
</a>
</li>
						<li class="d-inline">
<a href="https://radiology.extremelab.tech/#">
	<img src="{% static 'images/instagram.png' %}" width="40px">
</a>
</li>
						<li class="d-inline">
<a href="#">
	<img src="{% static 'images/youtube.png' %}" width="40px">
</a>
</li>
	  </ul>
</div>
</div>
	</div>

</div>

</div>
</div>

	{% endblock footer %}


	
	
	<script type="text/javascript" src="{% static 'js/analytics.js' %}" async></script>
	<!-- jQuery -->
<script type="text/javascript" async="" src="{% static 'js/analytics.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'js/sparkline.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'js/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'js/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.js' %}"></script>
<!-- DataTables -->
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/dataTables.fixedHeader.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/jszip.min.js' %}"></script>
<script src="{% static 'js/pdfmake.min.js' %}"></script>
<script src="{% static 'js/vfs_fonts.js' %}"></script>
<script src="{% static 'js/buttons.html5.min.js' %}"></script>
<script src="{% static 'js/buttons.print.min.js' %}"></script>
<script src="{% static 'js/buttons.colVis.min.js' %}"></script>
<!-- Toastr-->
<script src="{% static 'js/toastr.min.js' %}"></script>
<!-- Validate -->
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/jQuery.print.min.js' %}"></script>
<script src="{% static 'js/jquery.classyqr.min.js' %}"></script>
<script src="{% static 'js/select2.js' %}"></script>
<script src="{% static 'js/sweetalert.min.js' %}"></script>
	
	<script>
	$(document).ready(function(){
	$('#code').val('1593914720');
	});
	</script>
	
	<script src="{% static 'js/wm6kjlncgktzimpuaad5qetmtv9h1cui.js' %}" async></script>
	
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="{% static 'js/js' %}"></script>
	<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());
	
	gtag('config', 'UA-209769356-2');
	</script>
	


<script>
// Get the login form and the user type select element
const loginForm = document.getElementById("login-form");
const userTypeSelect = document.getElementById("user_type");

// Add an event listener to the login form submit event
loginForm.addEventListener("submit", function(event) {
// Prevent the default form submission behavior
event.preventDefault();

// Get the selected option's value and URL from the user type select element
const selectedOption = userTypeSelect.options[userTypeSelect.selectedIndex];
const selectedOptionValue = selectedOption.value;
const selectedOptionUrl = selectedOption.getAttribute("data-url");

// If a valid user type was selected, set the
	if (selectedOptionValue !== "") {
loginForm.action = selectedOptionUrl;
loginForm.submit();
}
});
</script>


<grammarly-desktop-integration data-grammarly-shadow-root="true">
</grammarly-desktop-integration>
	
</body>
</html>